In [1]:
#Read a *CSV file* and display the first 5 rows, last 5 rows, shape, and column names.
import pandas as pd
df=pd.read_csv('employees.csv')
print(df)

    Employee_ID Employee_Name Department       City  Salary Joining_Date
0          1001       Priya_1      Sales       Pune   52000   2022-08-02
1          1002       Meena_2         HR       Pune   41000   2020-05-16
2          1003        Riya_3      Sales      Delhi   62000   2022-10-17
3          1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4          1005        Isha_5      Sales      Delhi   47000   2021-10-31
..          ...           ...        ...        ...     ...          ...
95         1096      Meena_96         HR  Bangalore   91000   2024-03-10
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
98         1099      Priya_99    Finance  Hyderabad   89000   2023-06-01
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

[100 rows x 6 columns]

In [2]:
df.head()

   Employee_ID Employee_Name Department       City  Salary Joining_Date
0         1001       Priya_1      Sales       Pune   52000   2022-08-02
1         1002       Meena_2         HR       Pune   41000   2020-05-16
2         1003        Riya_3      Sales      Delhi   62000   2022-10-17
3         1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4         1005        Isha_5      Sales      Delhi   47000   2021-10-31

In [3]:
df.tail()

    Employee_ID Employee_Name Department       City  Salary Joining_Date
95         1096      Meena_96         HR  Bangalore   91000   2024-03-10
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
98         1099      Priya_99    Finance  Hyderabad   89000   2023-06-01
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

In [4]:
df.shape

(100, 6)

In [5]:
print(df.columns)

Index(['Employee_ID', 'Employee_Name', 'Department', 'City', 'Salary',
       'Joining_Date'],
      dtype='object')

In [12]:
df[df['Department'].isin(['Sales','HR'])]

    Employee_ID Employee_Name Department       City  Salary Joining_Date
0          1001       Priya_1      Sales       Pune   52000   2022-08-02
1          1002       Meena_2         HR       Pune   41000   2020-05-16
2          1003        Riya_3      Sales      Delhi   62000   2022-10-17
3          1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4          1005        Isha_5      Sales      Delhi   47000   2021-10-31
6          1007       Arjun_7      Sales  Bangalore   79000   2022-04-21
8          1009      Vikram_9      Sales  Hyderabad   59000   2024-05-14
11         1012       Amit_12      Sales      Delhi   53000   2024-06-15
13         1014      Kiran_14      Sales       Pune   49000   2022-12-13
14         1015       Neha_15      Sales  Bangalore   90000   2023-05-03
16         1017      Pooja_17         HR    Chennai   57000   2023-09-05
17         1018      Arjun_18      Sales      Delhi   75000   2020-03-05
18         1019       Riya_19         HR  Bangalore   64000   2019-12-17
20         1021     Ananya_21         HR  Hyderabad   86000   2020-10-26
26         1027      Meena_27         HR      Delhi   66000   2021-01-11
27         1028     Ananya_28      Sales  Bangalore   75000   2019-07-06
30         1031       Riya_31      Sales       Pune   81000   2024-06-11
35         1036       Ajay_36         HR    Chennai   83000   2022-06-01
37         1038      Divya_38      Sales  Hyderabad   94000   2020-10-25
38         1039       Neha_39         HR  Hyderabad   50000   2021-01-13
39         1040      Manoj_40      Sales  Hyderabad   81000   2023-12-04
45         1046      Meena_46         HR  Hyderabad   56000   2019-09-05
47         1048      Rahul_48      Sales       Pune   75000   2020-03-27
48         1049      Meena_49      Sales  Hyderabad   90000   2019-05-01
50         1051      Divya_51         HR      Delhi   43000   2022-10-02
54         1055     Ananya_55      Sales  Hyderabad   60000   2021-08-14
55         1056     Vikram_56      Sales  Bangalore   47000   2023-01-31
59         1060       Riya_60      Sales  Hyderabad   94000   2019-04-14
60         1061      Meena_61         HR     Mumbai   66000   2023-03-24
65         1066       Ajay_66      Sales      Delhi   82000   2020-08-30
68         1069     Nikhil_69      Sales  Bangalore   39000   2019-04-27
69         1070      Kiran_70         HR     Mumbai   42000   2022-05-03
70         1071      Manoj_71         HR      Delhi   73000   2024-04-12
71         1072       Isha_72      Sales     Mumbai   77000   2019-03-23
75         1076      Kiran_76      Sales     Mumbai   74000   2024-03-17
76         1077      Priya_77      Sales      Delhi   48000   2022-02-27
77         1078      Arjun_78         HR    Chennai   91000   2021-11-02
80         1081     Nikhil_81      Sales       Pune   87000   2022-09-01
81         1082       Neha_82      Sales  Bangalore   51000   2022-02-09
83         1084       Isha_84         HR       Pune   56000   2020-07-31
85         1086     Ananya_86      Sales       Pune   62000   2024-01-29
86         1087      Arjun_87      Sales  Hyderabad   56000   2023-08-26
89         1090      Kiran_90         HR      Delhi   37000   2019-08-18
91         1092      Rohit_92      Sales    Chennai   58000   2021-05-30
95         1096      Meena_96         HR  Bangalore   91000   2024-03-10
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

In [3]:
#4.Create a Pandas DataFrame and display employees whose salary is between ₹40,000 and ₹70,000.
df[df['Salary'].between(40000,70000)]

    Employee_ID Employee_Name Department       City  Salary Joining_Date
0          1001       Priya_1      Sales       Pune   52000   2022-08-02
1          1002       Meena_2         HR       Pune   41000   2020-05-16
2          1003        Riya_3      Sales      Delhi   62000   2022-10-17
3          1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4          1005        Isha_5      Sales      Delhi   47000   2021-10-31
5          1006        Riya_6    Finance  Bangalore   63000   2023-01-06
7          1008      Vikram_8         IT  Bangalore   48000   2021-05-15
8          1009      Vikram_9      Sales  Hyderabad   59000   2024-05-14
9          1010      Pooja_10         IT      Delhi   51000   2019-07-18
10         1011     Ananya_11    Finance      Delhi   42000   2023-07-11
11         1012       Amit_12      Sales      Delhi   53000   2024-06-15
12         1013       Isha_13         IT      Delhi   47000   2023-08-26
13         1014      Kiran_14      Sales       Pune   49000   2022-12-13
16         1017      Pooja_17         HR    Chennai   57000   2023-09-05
18         1019       Riya_19         HR  Bangalore   64000   2019-12-17
21         1022       Amit_22         IT  Hyderabad   48000   2020-10-08
23         1024       Amit_24    Finance  Bangalore   51000   2021-10-19
24         1025      Meena_25  Marketing      Delhi   51000   2019-10-13
25         1026      Manoj_26    Finance      Delhi   60000   2023-03-10
26         1027      Meena_27         HR      Delhi   66000   2021-01-11
28         1029      Kavya_29  Marketing  Hyderabad   59000   2019-11-24
29         1030       Isha_30    Finance      Delhi   51000   2021-02-20
31         1032       Riya_32         IT       Pune   56000   2019-08-23
32         1033       Neha_33    Finance  Bangalore   64000   2019-08-17
33         1034      Arjun_34  Marketing  Bangalore   67000   2019-01-07
34         1035      Priya_35         IT       Pune   67000   2024-02-13
38         1039       Neha_39         HR  Hyderabad   50000   2021-01-13
40         1041      Kiran_41  Marketing  Bangalore   43000   2021-09-22
41         1042      Divya_42  Marketing  Bangalore   51000   2022-09-13
44         1045      Pooja_45    Finance      Delhi   63000   2022-08-23
45         1046      Meena_46         HR  Hyderabad   56000   2019-09-05
49         1050      Kiran_50  Marketing  Bangalore   52000   2020-11-07
50         1051      Divya_51         HR      Delhi   43000   2022-10-02
51         1052      Manoj_52  Marketing     Mumbai   50000   2023-01-21
52         1053      Divya_53    Finance  Bangalore   41000   2023-05-26
53         1054      Kavya_54         IT     Mumbai   61000   2019-07-18
54         1055     Ananya_55      Sales  Hyderabad   60000   2021-08-14
55         1056     Vikram_56      Sales  Bangalore   47000   2023-01-31
56         1057       Riya_57    Finance  Bangalore   62000   2020-01-25
58         1059      Kiran_59    Finance      Delhi   41000   2024-03-05
60         1061      Meena_61         HR     Mumbai   66000   2023-03-24
61         1062       Ajay_62    Finance  Hyderabad   45000   2021-09-12
64         1065       Riya_65    Finance  Bangalore   47000   2024-05-14
67         1068      Divya_68  Marketing      Delhi   45000   2022-04-11
69         1070      Kiran_70         HR     Mumbai   42000   2022-05-03
73         1074       Ajay_74         IT  Bangalore   51000   2020-06-18
74         1075      Rohit_75         IT     Mumbai   55000   2021-03-21
76         1077      Priya_77      Sales      Delhi   48000   2022-02-27
78         1079      Meena_79         IT    Chennai   45000   2019-05-21
81         1082       Neha_82      Sales  Bangalore   51000   2022-02-09
82         1083      Priya_83  Marketing  Bangalore   52000   2019-08-25
83         1084       Isha_84         HR       Pune   56000   2020-07-31
84         1085      Arjun_85  Marketing     Mumbai   51000   2020-02-21
85         1086     Ananya_86      Sales       Pune   62000   2024-01-29
86         1087      Arjun_87      Sales  Hyderabad   56000   2023-08-26
90         1091      Pooja_91  Marketing      Delhi   44000   2023-09-06
91         1092      Rohit_92      Sales    Chennai   58000   2021-05-30
94         1095      Kavya_95  Marketing       Pune   44000   2023-11-27
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

In [8]:
df['Tax']=df['Salary']*0.05
df

,Employee_ID,Employee_Name,Department,City,Salary,Joining_Date,Tax
0,1001,Priya_1,Sales,Pune,52000,2022-08-02,2600.0
1,1002,Meena_2,HR,Pune,41000,2020-05-16,2050.0
2,1003,Riya_3,Sales,Delhi,62000,2022-10-17,3100.0
3,1004,Rahul_4,Sales,Bangalore,49000,2019-03-07,2450.0
4,1005,Isha_5,Sales,Delhi,47000,2021-10-31,2350.0
...,...,...,...,...,...,...,...
95,1096,Meena_96,HR,Bangalore,91000,2024-03-10,4550.0
96,1097,Rahul_97,HR,Pune,94000,2021-04-24,4700.0
97,1098,Kavya_98,HR,Chennai,45000,2020-11-11,2250.0
98,1099,Priya_99,Finance,Hyderabad,89000,2023-06-01,4450.0
99,1100,Meena_100,HR,Mumbai,57000,2021-08-21,2850.0

In [14]:
#Sort employees by salary (descending) and name (ascending)
df=df.sort_values(by=['Salary','Employee_Name'],ascending=[False,True])
print(df)

    Employee_ID Employee_Name Department       City  Salary Joining_Date  \
37         1038      Divya_38      Sales  Hyderabad   94000   2020-10-25
42         1043       Isha_43    Finance  Bangalore   94000   2021-12-16
72         1073      Manoj_73  Marketing    Chennai   94000   2022-04-10
62         1063      Rahul_63    Finance    Chennai   94000   2021-02-15
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
..          ...           ...        ...        ...     ...          ...
1          1002       Meena_2         HR       Pune   41000   2020-05-16
68         1069     Nikhil_69      Sales  Bangalore   39000   2019-04-27
66         1067     Ananya_67         IT  Hyderabad   38000   2022-01-15
89         1090      Kiran_90         HR      Delhi   37000   2019-08-18
88         1089       Riya_89    Finance      Delhi   35000   2021-06-23

       Tax
37  4700.0
42  4700.0
72  4700.0
62  4700.0
96  4700.0
..     ...
1   2050.0
68  1950.0
66  1900.0
89  1850.0
88  1750.0

[100 rows x 7 columns]