In [ ]:
#Read a *CSV file* and display the first 5 rows, last 5 rows, shape, and column names.
import pandas as pd
df=pd.read_csv('employees.csv')
print(df)

    Employee_ID Employee_Name Department       City  Salary Joining_Date
0          1001       Priya_1      Sales       Pune   52000   2022-08-02
1          1002       Meena_2         HR       Pune   41000   2020-05-16
2          1003        Riya_3      Sales      Delhi   62000   2022-10-17
3          1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4          1005        Isha_5      Sales      Delhi   47000   2021-10-31
..          ...           ...        ...        ...     ...          ...
95         1096      Meena_96         HR  Bangalore   91000   2024-03-10
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
98         1099      Priya_99    Finance  Hyderabad   89000   2023-06-01
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

[100 rows x 6 columns]

In [2]:
df.head()

   Employee_ID Employee_Name Department       City  Salary Joining_Date
0         1001       Priya_1      Sales       Pune   52000   2022-08-02
1         1002       Meena_2         HR       Pune   41000   2020-05-16
2         1003        Riya_3      Sales      Delhi   62000   2022-10-17
3         1004       Rahul_4      Sales  Bangalore   49000   2019-03-07
4         1005        Isha_5      Sales      Delhi   47000   2021-10-31

In [3]:
df.tail()

    Employee_ID Employee_Name Department       City  Salary Joining_Date
95         1096      Meena_96         HR  Bangalore   91000   2024-03-10
96         1097      Rahul_97         HR       Pune   94000   2021-04-24
97         1098      Kavya_98         HR    Chennai   45000   2020-11-11
98         1099      Priya_99    Finance  Hyderabad   89000   2023-06-01
99         1100     Meena_100         HR     Mumbai   57000   2021-08-21

In [4]:
df.shape

(100, 6)

In [5]:
print(df.columns)

Index(['Employee_ID', 'Employee_Name', 'Department', 'City', 'Salary',
       'Joining_Date'],
      dtype='object')