In [7]:
#Create a NumPy array and find the sum, mean, maximum, and minimum values.
import numpy as np
arr=np.array([2,4,6,8,10])
print(f"The sum of the array: {arr.sum()}")
print(f"The mean of the array: {arr.mean()}")
print(f"The maximam number of the array {arr.max()}")
print(f"The minimum of the array: {arr.min()}")

The sum of the array: 30
The mean of the array: 6.0
The maximam number of the array 10
The minimum of the array: 2

In [12]:
import pandas as pd

data={
    "Emp_ID":[101,102,103,104,105,106],
    "Name":["Harsha","Rahul","Priya","Amit","Rakesh","Anudeep"],
    "Departement":["IT","HR","Finance","IT","Marketing","HR"],
    "Salary":[60000, 45000, 75000, None, 52000, 48000]
}

df=pd.DataFrame(data)
print(df)

   Emp_ID     Name Departement   Salary
0     101   Harsha          IT  60000.0
1     102    Rahul          HR  45000.0
2     103    Priya     Finance  75000.0
3     104     Amit          IT      NaN
4     105   Rakesh   Marketing  52000.0
5     106  Anudeep          HR  48000.0

In [16]:
df[df['Salary']>50000]

   Emp_ID    Name Departement   Salary
0     101  Harsha          IT  60000.0
2     103   Priya     Finance  75000.0
4     105  Rakesh   Marketing  52000.0

In [23]:
df['Bonus']=df['Salary']*0.10
df

   Emp_ID     Name Departement   Salary   Bonus
0     101   Harsha          IT  60000.0  6000.0
1     102    Rahul          HR  45000.0  4500.0
2     103    Priya     Finance  75000.0  7500.0
3     104     Amit          IT      NaN     NaN
4     105   Rakesh   Marketing  52000.0  5200.0
5     106  Anudeep          HR  48000.0  4800.0

In [24]:
df=df.dropna()
df

   Emp_ID     Name Departement   Salary   Bonus
0     101   Harsha          IT  60000.0  6000.0
1     102    Rahul          HR  45000.0  4500.0
2     103    Priya     Finance  75000.0  7500.0
4     105   Rakesh   Marketing  52000.0  5200.0
5     106  Anudeep          HR  48000.0  4800.0